name: Expo Publish
on:
  push:
    branches:
      - main
      - feat/*
jobs:
  publish:
    name: Install and publish
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - uses: expo/expo-github-action@v6
        with:
          expo-version: 4.x
          token: ${{ secrets.EXPO_TOKEN }}
      - name: replace google map api key
        run: find app/app.json -type f -exec sed -i ''s/GOOGLE_MAPS_KEY/${{ secrets.GOOGLE_MAPS_API_KEY }}/g'' {} \;
      - run: npm i
      - run: npm i -g expo-cli
      - run: npm run test
      - run: npm run publish